import { NextResponse } from 'next/server';
import { createServerClient, type CookieOptions } from '@supabase/ssr';
import { cookies } from 'next/headers';
import { logger } from '@/lib/logger'; // Assuming logger is in lib

// Define the type for a research project based on your schema
// This should ideally align with types generated from your Supabase schema (e.g., database.types.ts)
interface ResearchProject {
  id?: string; // UUID, usually generated by DB
  title: string;
  description?: string;
  user_id?: string; // Will be set to the authenticated user's ID
  created_at?: string;
  updated_at?: string;
}

export async function GET(request: Request) {
  const cookieStore = cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value, ...options })
          } catch (error) {
            // The `set` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
        remove(name: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value: '', ...options })
          } catch (error) {
            // The `delete` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
      },
    }
  );

  try {
    const { data: { session }, error: sessionError } = await supabase.auth.getSession();

    if (sessionError) {
      logger.error('Error getting session in GET /api/research-projects', { error: sessionError });
      return NextResponse.json({ error: 'Failed to get session: ' + sessionError.message }, { status: 500 });
    }
    
    // RLS policies will ensure users only see projects they are allowed to.
    // If a user is not authenticated, they might see projects allowed by "Enable read access for all users" (USING (true))
    // If they are authenticated, other policies might apply.
    const { data, error } = await supabase
      .from('research_projects')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      logger.error('Error fetching research projects', { error });
      return NextResponse.json({ error: 'Failed to fetch research projects: ' + error.message }, { status: 500 });
    }

    return NextResponse.json(data);
  } catch (e: any) {
    logger.error('Unexpected error in GET /api/research-projects', { error: e.message, stack: e.stack });
    return NextResponse.json({ error: 'An unexpected error occurred: ' + e.message }, { status: 500 });
  }
}

export async function POST(request: Request) {
  const cookieStore = cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value, ...options })
          } catch (error) {
            // The `set` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
        remove(name: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value: '', ...options })
          } catch (error) {
            // The `delete` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
      },
    }
  );

  try {
    const { data: { user }, error: userError } = await supabase.auth.getUser();

    if (userError || !user) {
      logger.warn('Unauthorized attempt to create research project', { error: userError?.message });
      return NextResponse.json({ error: 'You must be logged in to create a research project.' }, { status: 401 });
    }

    let projectData: Partial<ResearchProject>;
    try {
      projectData = await request.json();
    } catch (e) {
      logger.warn('Invalid JSON in POST /api/research-projects', { error: (e as Error).message });
      return NextResponse.json({ error: 'Invalid request body: Malformed JSON.' }, { status: 400 });
    }
    

    if (!projectData.title) {
      return NextResponse.json({ error: 'Title is required.' }, { status: 400 });
    }

    const newProject: Omit<ResearchProject, 'id' | 'created_at' | 'updated_at'> = {
      title: projectData.title,
      description: projectData.description,
      user_id: user.id, // Set the owner to the currently authenticated user
    };

    const { data, error } = await supabase
      .from('research_projects')
      .insert(newProject)
      .select()
      .single(); // Assuming you want the created project back

    if (error) {
      logger.error('Error creating research project', { error, userId: user.id, projectTitle: newProject.title });
      // More specific error handling based on Supabase error codes could be added here
      // e.g. if (error.code === '23503') // foreign key violation
      return NextResponse.json({ error: 'Failed to create research project: ' + error.message }, { status: 500 });
    }

    return NextResponse.json(data, { status: 201 });
  } catch (e: any) {
    logger.error('Unexpected error in POST /api/research-projects', { error: e.message, stack: e.stack });
    return NextResponse.json({ error: 'An unexpected error occurred: ' + e.message }, { status: 500 });
  }
}
