export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      research_projects: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string; // Usually generated by Supabase
          user_id: string;
          title: string;
          description?: string | null;
          created_at?: string; // Usually handled by Supabase
          updated_at?: string; // Usually handled by Supabase
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          // Example relationship, adjust if you have a users table in public schema
          // {
          //   foreignKeyName: "research_projects_user_id_fkey";
          //   columns: ["user_id"];
          //   referencedRelation: "users"; // Assuming a 'users' table
          //   referencedColumns: ["id"];
          // }
        ];
      };
      // Add other table definitions here as your schema grows
    };
    Views: {
      // Define any database views here
    };
    Functions: {
      // Define any database functions here
    };
  };
}
