export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface ResearchProject {
  id: string;
  user_id: string;
  title: string;
  description: string | null;
  created_at: string;
  updated_at: string;
  due_date?: string | null;
  priority?: 'low' | 'medium' | 'high';
  tags?: string[];
  status?: 'not_started' | 'in_progress' | 'completed' | 'on_hold' | 'cancelled';
  category?: string;
  estimated_hours?: number;
  actual_hours?: number;
  start_date?: string;
  completion_date?: string;
  objectives?: string[];
  methodology?: string;
  collaborators?: string[];
  external_links?: string[];
  funding_source?: string;
  budget?: number;
}

export interface Database {
  public: {
    Tables: {
      user_preferences: {
        Row: {
          id: string;
          user_id: string;
          preferences: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          preferences: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_preferences_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      research_projects: {
        Row: ResearchProject;
        Insert: {
          id?: string; // Usually generated by Supabase
          user_id: string;
          title: string;
          description?: string | null;
          created_at?: string; // Usually handled by Supabase
          updated_at?: string; // Usually handled by Supabase
          due_date?: string | null;
          priority?: 'low' | 'medium' | 'high';
          tags?: string[];
          status?: 'not_started' | 'in_progress' | 'completed' | 'on_hold' | 'cancelled';
          category?: string;
          estimated_hours?: number;
          actual_hours?: number;
          start_date?: string;
          completion_date?: string;
          objectives?: string[];
          methodology?: string;
          collaborators?: string[];
          external_links?: string[];
          funding_source?: string;
          budget?: number;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
          due_date?: string | null;
          priority?: 'low' | 'medium' | 'high';
          tags?: string[];
          status?: 'not_started' | 'in_progress' | 'completed' | 'on_hold' | 'cancelled';
          category?: string;
          estimated_hours?: number;
          actual_hours?: number;
          start_date?: string;
          completion_date?: string;
          objectives?: string[];
          methodology?: string;
          collaborators?: string[];
          external_links?: string[];
          funding_source?: string;
          budget?: number;
        };
        Relationships: [
          // Example relationship, adjust if you have a users table in public schema
          // {
          //   foreignKeyName: "research_projects_user_id_fkey";
          //   columns: ["user_id"];
          //   referencedRelation: "users"; // Assuming a 'users' table
          //   referencedColumns: ["id"];
          // }
        ];
      };
      // Add other table definitions here as your schema grows
    };
    Views: {
      // Define any database views here
    };
    Functions: {
      // Define any database functions here
    };
  };
}
