#!/bin/bash
# Production Deployment Script for Zenith Research Platform
# This script automates the deployment of the Zenith Research Platform to production

set -e # Exit immediately if a command exits with a non-zero status

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to print section headers
print_section() {
  echo -e "\n${YELLOW}==== $1 ====${NC}\n"
}

# Function to print success messages
print_success() {
  echo -e "${GREEN}✓ $1${NC}"
}

# Function to print error messages
print_error() {
  echo -e "${RED}✗ $1${NC}"
  exit 1
}

# Function to check if command exists
command_exists() {
  command -v "$1" >/dev/null 2>&1
}

# Check for required tools
print_section "Checking required tools"

if ! command_exists terraform; then
  print_error "Terraform is not installed. Please install Terraform and try again."
fi

if ! command_exists vercel; then
  print_error "Vercel CLI is not installed. Please install Vercel CLI and try again."
fi

if ! command_exists npm; then
  print_error "npm is not installed. Please install Node.js and npm and try again."
fi

print_success "All required tools are installed"

# Check for required environment variables
print_section "Checking required environment variables"

required_env_vars=(
  "AWS_ACCESS_KEY_ID"
  "AWS_SECRET_ACCESS_KEY"
  "VERCEL_TOKEN"
  "SUPABASE_URL"
  "SUPABASE_SERVICE_ROLE_KEY"
)

for var in "${required_env_vars[@]}"; do
  if [ -z "${!var}" ]; then
    print_error "Environment variable $var is not set. Please set it and try again."
  fi
done

print_success "All required environment variables are set"

# Create deployment directory
DEPLOY_DIR="deploy-$(date +%Y%m%d%H%M%S)"
mkdir -p "$DEPLOY_DIR"
cd "$DEPLOY_DIR"

# Clone repository
print_section "Cloning repository"
git clone https://github.com/your-organization/zenith.git .
print_success "Repository cloned successfully"

# Install dependencies
print_section "Installing dependencies"
npm ci
print_success "Dependencies installed successfully"

# Build application
print_section "Building application"
npm run build
print_success "Application built successfully"

# Deploy infrastructure with Terraform
print_section "Deploying infrastructure with Terraform"

cd terraform
terraform init

echo "Planning Terraform deployment..."
terraform plan -var-file=environments/production.tfvars -out=production.tfplan

echo "Applying Terraform deployment..."
terraform apply production.tfplan

# Store Terraform outputs for later use
REDIS_ENDPOINT=$(terraform output -raw redis_primary_endpoint)
S3_BUCKET=$(terraform output -raw s3_bucket_name)
DOMAIN_NAME=$(terraform output -raw deployment_domain)

cd ..
print_success "Infrastructure deployed successfully"

# Run database migrations
print_section "Running database migrations"
npm run db:migrate:production
print_success "Database migrations completed successfully"

# Update environment variables for Vercel
print_section "Updating environment variables for Vercel"

# Create .env.production file with Terraform outputs
cat > .env.production << EOF
# Production environment variables
# Generated by deploy-production.sh on $(date)

# API URLs
NEXT_PUBLIC_API_URL=https://api.${DOMAIN_NAME}
NEXT_PUBLIC_APP_URL=https://${DOMAIN_NAME}

# Redis
REDIS_URL=${REDIS_ENDPOINT}:6379

# S3
S3_BUCKET=${S3_BUCKET}
S3_REGION=$(terraform output -raw deployment_region)

# Other environment variables
NODE_ENV=production
EOF

print_success "Environment variables updated successfully"

# Deploy to Vercel
print_section "Deploying to Vercel"
vercel --prod --token "$VERCEL_TOKEN"
print_success "Deployed to Vercel successfully"

# Verify deployment
print_section "Verifying deployment"

# Check if the website is accessible
if curl -s --head "https://${DOMAIN_NAME}" | grep "200 OK" > /dev/null; then
  print_success "Website is accessible"
else
  print_error "Website is not accessible"
fi

# Check if the API is accessible
if curl -s --head "https://api.${DOMAIN_NAME}/api/health" | grep "200 OK" > /dev/null; then
  print_success "API is accessible"
else
  print_error "API is not accessible"
fi

# Final success message
print_section "Deployment completed successfully"
echo "The Zenith Research Platform has been deployed to production."
echo "Website URL: https://${DOMAIN_NAME}"
echo "API URL: https://api.${DOMAIN_NAME}"
echo ""
echo "Next steps:"
echo "1. Verify all features work as expected in production"
echo "2. Set up monitoring and alerting"
echo "3. Conduct final testing"
echo "4. Prepare for public launch"

exit 0
